import { arSA } from "@clerk/localizations";

export const softaiArabicClerkLocalization = {
  ...arSA,
  badge__activePlan: "مفعّلة",
  badge__pastDuePlan: "متأخرة الدفع",
  badge__upcomingPlan: "قادمة",
  billing: {
    ...arSA.billing,
    addPaymentMethod__label: "إضافة طريقة دفع",
    alwaysFree: "مجانية دائماً",
    annually: "سنوياً",
    availableFeatures: "المزايا المتاحة",
    billedAnnually: "تدفع سنوياً",
    billedMonthlyOnly: "تدفع شهرياً فقط",
    billedAnnuallyOnly: "تدفع سنوياً فقط",
    cancelSubscription: "إلغاء الاشتراك",
    cancelSubscriptionTitle: "إلغاء اشتراك {{plan}}؟",
    checkout: { ...arSA.billing?.checkout, perMonth: "شهرياً", title: "الدفع", title__subscriptionSuccessful: "تم الاشتراك بنجاح" },
    credit: "رصيد",
    defaultFreePlanActive: "أنت حالياً على الخطة المجانية",
    free: "مجانية",
    getStarted: "ابدأ الآن",
    manage: "إدارة",
    manageSubscription: "إدارة الاشتراك",
    month: "شهر",
    monthAbbreviation: "شهر",
    monthly: "شهرياً",
    pastDue: "متأخرة الدفع",
    pay: "ادفع {{amount}}",
    paymentMethods__label: "طرق الدفع",
    highlightedPlanBadge: "الأكثر شيوعاً",
    pricingTable: { ...arSA.billing?.pricingTable, billingCycle: "دورة الفوترة", included: "يشمل" },
    reSubscribe: "إعادة الاشتراك",
    seeAllFeatures: "عرض كل المزايا",
    startFreeTrial: "ابدأ التجربة المجانية",
    subscribe: "اشترك",
    subscriptionDetails: {
      ...arSA.billing?.subscriptionDetails,
      beginsOn: "يبدأ في",
      currentBillingCycle: "دورة الفوترة الحالية",
      endsOn: "ينتهي في",
      nextPaymentAmount: "قيمة الدفعة القادمة",
      nextPaymentOn: "موعد الدفعة القادمة",
      renewsAt: "يتجدد في",
      subscribedOn: "تم الاشتراك في",
      title: "الاشتراك",
    },
    subtotal: "المجموع الفرعي",
    switchPlan: "الانتقال إلى هذه الخطة",
    switchToAnnual: "التحويل إلى سنوي",
    switchToMonthly: "التحويل إلى شهري",
    totalDue: "الإجمالي المستحق",
    totalDueToday: "المستحق اليوم",
    viewFeatures: "عرض المزايا",
    viewPayment: "عرض الدفع",
    year: "سنة",
    yearAbbreviation: "سنة",
  },
  userProfile: {
    ...arSA.userProfile,
    billingPage: {
      ...arSA.userProfile?.billingPage,
      paymentHistorySection: {
        ...arSA.userProfile?.billingPage?.paymentHistorySection,
        empty: "لا يوجد سجل دفع",
        notFound: "لم يتم العثور على محاولة الدفع",
        tableHeader__amount: "المبلغ",
        tableHeader__date: "التاريخ",
        tableHeader__status: "الحالة",
      },
      paymentMethodsSection: {
        ...arSA.userProfile?.billingPage?.paymentMethodsSection,
        actionLabel__default: "اجعلها الافتراضية",
        actionLabel__remove: "إزالة",
        add: "إضافة طريقة دفع جديدة",
        addSubtitle: "أضف طريقة دفع جديدة إلى حسابك.",
        cancelButton: "إلغاء",
        formButtonPrimary__add: "إضافة طريقة الدفع",
        formButtonPrimary__pay: "ادفع {{amount}}",
        payWithTestCardButton: "الدفع ببطاقة اختبار",
        title: "طرق الدفع",
      },
      start: {
        ...arSA.userProfile?.billingPage?.start,
        headerTitle__payments: "المدفوعات",
        headerTitle__plans: "الخطط",
        headerTitle__statements: "الكشوفات",
        headerTitle__subscriptions: "الاشتراك",
      },
      statementsSection: {
        ...arSA.userProfile?.billingPage?.statementsSection,
        empty: "لا توجد كشوفات لعرضها",
        itemCaption__paidForPlan: "تم الدفع لخطة {{plan}} {{period}}",
        itemCaption__proratedCredit: "رصيد نسبي لاستخدام جزئي من الاشتراك السابق",
        itemCaption__payerCredit: "رصيد من حسابك",
        itemCaption__subscribedAndPaidForPlan: "تم الاشتراك والدفع لخطة {{plan}} {{period}}",
        tableHeader__amount: "المبلغ",
        tableHeader__date: "التاريخ",
        title: "الكشوفات",
        totalPaid: "إجمالي المدفوع",
      },
      subscriptionsListSection: {
        ...arSA.userProfile?.billingPage?.subscriptionsListSection,
        actionLabel__manageSubscription: "إدارة",
        actionLabel__newSubscription: "اشترك في خطة",
        actionLabel__switchPlan: "تغيير الخطة",
        tableHeader__edit: "تعديل",
        tableHeader__plan: "الخطة",
        tableHeader__startDate: "تاريخ البدء",
        title: "الاشتراك",
      },
      subscriptionsSection: { ...arSA.userProfile?.billingPage?.subscriptionsSection, actionLabel__default: "إدارة" },
      switchPlansSection: { ...arSA.userProfile?.billingPage?.switchPlansSection, title: "تغيير الخطة" },
      title: "الفوترة",
    },
    navbar: {
      ...arSA.userProfile?.navbar,
      account: "الملف الشخصي",
      apiKeys: "مفاتيح API",
      billing: "الفوترة",
      description: "إدارة معلومات حسابك.",
      security: "الأمان",
      title: "الحساب",
    },
  },
};
