export const runwayClerkAppearance = {
  variables: {
    colorBackground: "oklch(0.105 0.008 260)",
    colorForeground: "oklch(0.965 0.004 260)",
    colorPrimary: "oklch(0.58 0.22 280)",
    colorText: "oklch(0.965 0.004 260)",
    colorTextSecondary: "oklch(0.76 0.016 260)",
    colorInputBackground: "oklch(0.075 0.007 260)",
    colorInputText: "oklch(0.965 0.004 260)",
    colorNeutral: "oklch(0.58 0.018 260)",
    borderRadius: "12px",
  },
  elements: {
    rootBox: "w-full",
    card: "bg-transparent shadow-none border-none text-text",
    cardBox: "w-full rounded-none bg-transparent shadow-none border-none",
    headerTitle: "text-text",
    headerSubtitle: "text-text-secondary",
    navbar: "bg-surface border-border",
    navbarMobileMenuButton: "text-text-secondary hover:text-text",
    navbarButton: "text-text-secondary hover:bg-surface-raised hover:text-text",
    navbarButtonIcon: "text-text-tertiary",
    pageScrollBox: "bg-transparent",
    page: "bg-transparent text-text",
    profileSection: "border-border",
    profileSectionTitle: "text-text",
    profileSectionContent: "text-text-secondary",
    profileSectionPrimaryButton: "btn btn-primary",
    formButtonPrimary: "btn btn-primary",
    formFieldLabel: "text-text-secondary",
    formFieldInput: "control-field",
    accordionTriggerButton: "text-text hover:bg-surface-raised",
    accordionContent: "text-text-secondary",
    badge: "border-border bg-surface-raised text-text-secondary",
    dividerLine: "bg-border",
    modalContent: "bg-surface text-text border border-border",
    modalCloseButton: "text-text-secondary hover:text-text",
  },
} as const;
